### ISSUE TITLE
[WISH] RS-422 serial ports over DB9

### ISSUE THREAD

**Issue by egrath** [mist-devel/plus_too#1]
Would it be possible to repurpose the two DB9 ports to work as RS422 serial connections to let the PlusToo core access external devices like serially attached printers? As classic Mac's don't have gameports this would'nt result in loss of hardware functionality.

**Comment by gyurco** [comment]
As the DB9 ports are connected to the MCU, not the FPGA, it's not really feasible. The joystick and RS422 pinouts even have a conflict. However there are USB-RS422 converters, which can be supported in the firmware, if anyone with enough interest wants to work on it (usually the later doesn't happen).

**Comment by egrath** [comment]
Thanks for the information, so it's probably something not going to happen anytime soon :-)
