### ISSUE TITLE
Backport recent MISTer changes

### ISSUE THREAD

**Issue by egrath** [mist-devel/plus_too#2]
The MISTer port of plus_too has implemented various fixes for the core which would be nice to also have in the MIST version.

https://github.com/MiSTer-devel/MacPlus_MiSTer/commits/master

**Comment by gyurco** [comment]
More concrete?
Most of those changes (SE mode, ADB, etc...) were ported from _my_ work on MiST.

**Comment by egrath** [comment]
For example the recent Floppy access fix:

https://github.com/MiSTer-devel/MacPlus_MiSTer/commit/daa1bc86fbbb15d8122de6fe11ec68db86e8a7eb

There seemed to be a lot more fixes according to the commit logs (as they are newer than those in this repository), but after a quick check it seems that they are already in here. So currently the Floppy access fix is the only one ... sorry for the inconvinience caused by this ticket, was probably opened to hastly.

**Comment by gyurco** [comment]
And why does it need a fix?
The mentioned patch just separates the disk OE from the rom OE, because the ROM (SE or Plus) can be selected in the OSD. On MiST, only one is loaded at boot.

**Comment by gyurco** [comment]
BTW, if you found a problem in the core, then please describe it in the issue, just mentioning some random patches in MiSTer doesn't help, as they don't necessarily relevant here.
