### ISSUE TITLE
Wrong scancode for up-arrow key when using Mac Plus ROM?

### ISSUE THREAD

**Issue by robinsonb5** [mist-devel/plus_too#4]
I've just ported this core to TC64, and noticed when using the Mac Plus ROM from https://github.com/ManuFerHi/SiDi-FPGA/tree/master/Cores/Computer/Plus_too that the up-arrow key on the keyboard produces a "+" instead of moving the cursor.

I don't know if this is due to the ROM, the OS revision (I'm using a set of System 6.0.8 800k disk images found on Archive.org and installed to an HD image) or whether it's a bug in the core's kerboard mapping.

It's really hard to find definitive information on pre-ADB keyboards, but a study of historic MESS sources leads me to believe the scancode should be 9'h11b, not 9'10b - and making this change does indeed seem to fix it - see the commit at 
https://github.com/robinsonb5/plus_too/commit/aa3bf934b7862b39c6b6f27d9b440cc92a4e5b4e

I haven't created a PR simply because I'm not confident this is correct and there isn't some other cause for the apparent scancode mismatch.

**Comment by gyurco** [comment]
Maybe you're right, here's also 1b:
https://github.com/trekawek/mac-plus-ps2/blob/417ad73bb89ec6a96e4970e4a3d8206232acf18d/mac_plus_ps2/keymap.ino#L82

**Comment by robinsonb5** [comment]
Interesting. Makes me wonder why no-one's spotted it before, though. Is everyone using Mac SE ROMs and thus the ADB keyboard codes?

**Comment by gyurco** [comment]
When there was no ADB support, I don't remember I could not use the up key in games. Strange, maybe they don't care about the difference between + and up?
However I think it would be worth to add the + key, too, as it's there on the original keyboard:
https://deskthority.net/wiki/images/7/72/Apple_M0110A_top.jpg

**Comment by robinsonb5** [comment]
I've just tested the keypad keys, and some of those are wrong, too:
'/' is mapped to 9'h11b, so causes a cursor up
'*' is mapped to 9'h105, and triggers a cursor right
'+' is mapped to 9'h10d which is cursor left

Looking at the keyboard adapter source you posted above, it looks like those three should be prefixed with 0x200, not 0x100.
Edit: correction - those three keys need a two-byte prefix of 0x71, 0x79 instead of just 0x79.

Very weird - they must have been tested at some point?

**Comment by gyurco** [comment]
Probably it was considered good enough :)
As I see, two byte prefixes are not even supported (doesn't look too hard to add them).

**Comment by robinsonb5** [comment]
Interesting - it turns out that 0x71 is just the keycode for Shift. Sending 0x71 before the troublesome keycodes does indeed fix them, but the shift keypress needs releasing afterwards.

But since the 0x10b scancode that used to be on cursor-up accidentally triggered a "+" keypress without the extra prefix, I'm wondering if the 0x71 prefix is correct, or just a side effect of how the key decoding is done - and maybe there are correct scancodes for those keys that need to be discovered?

Edit: OK it makes more sense now:
The original M0110 keyboard could be used with an optional M0120 keypad, which had four cursor keys around the numpad. Those keys emitted calc functions (+ * / .) if the shift key was pressed.
The M0110A integrated the numpad and added dedicated cursor keys. The numpad calc keys now don't need shifting to access them, but those four keys still emit a shift code when pressed.

https://deskthority.net/wiki/Apple_M0120
Some good information here:
https://github.com/tmk/tmk_keyboard/wiki/Apple-M0110-Keyboard-Protocol

**Comment by robinsonb5** [comment]
Seems to be working well for me now - PR created.
